version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5435/rx_restaurant
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rx_restaurant
    ports:
      - 5435:5432
    volumes:
      - ~/rx/data/:/var/lib/rx/postgresql/data
