version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgresql:5432/rx_restaurant
    depends_on:
      - postgresql
    volumes:
      - .:/dist/app
    command: >
      sh -c "npx sequelize-cli db:migrate && npm start"

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rx_restaurant
    ports:
      - 5436:5432
    volumes:
      - ~/rx/data/:/var/lib/rx/postgresql/data
